_BASE_: "../Base-RCNN-FPN.yaml"
SEED: 100
MODEL:
  WEIGHTS: "results/LVISv0.5/base_R101_2/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: True
  ROI_HEADS:
    NUM_CLASSES: 1230
    SCORE_THRESH_TEST: 0.0001
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
    FREEZE: True
#  PROPOSAL_GENERATOR:
#    FREEZE: True
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("lvis_v0.5_train_10shot",)
  TEST: ("lvis_v0.5_val_all",)
  SHOT: 10
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (10000,)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 0
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
#  EVAL_PERIOD: 500
#DATALOADER:
#  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
#  REPEAT_THRESHOLD: 0.001
SETTING: 'Incremental'
PHASE: 2
METHOD: 'ft'
OUTPUT_DIR:
  "results/fewshot/LVISv0.5/R101_ft_1"
