_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  BACKBONE:
    FREEZE_AT: 3
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: False
    POOLER_RESOLUTION: 7
  ROI_HEADS:
    NUM_CLASSES: 15
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.75
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_split1_base', 'voc_2012_trainval_split1_base')
  TEST: ('voc_2007_test_split1_all',)
SOLVER:
  STEPS: (10000, 13300)
  MAX_ITER: 15000
  WARMUP_ITERS: 100
  WEIGHT_DECAY: 5e-5
PHASE: 1
OUTPUT_DIR: "/Path/to/Output/Dir"