_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
  ROI_HEADS:
    NUM_CLASSES: 20
    BATCH_SIZE_PER_IMAGE: 256
    SCORE_THRESH_TEST: 0.01
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
    FREEZE: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_split1_1shot', 'voc_2012_trainval_split1_1shot')
  TEST: ('voc_2007_test_split1_all',)
SOLVER:
  BASE_LR: 0.02
  STEPS: (300,)
  WARMUP_ITERS: 5
  MAX_ITER: 300
  CHECKPOINT_PERIOD: 100
SETTING: 'Incremental'
PHASE: 2
METHOD: 'ours'
INIT_ITERS: 10
OUTPUT_DIR: "/Path/to/Output/Dir"
